version: "3.8"

x-blanball-chat-api-common-dev: &blanball-chat-api-common-dev
  env_file:
    - .env
  entrypoint: scripts/entrypoint.sh
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/usr/src/blanball-chat
  networks:
    - blaball-chat-network-dev
    - blanball-chat-connection-network-dev
  depends_on:
    blanball-chat-db-dev:
      condition: service_healthy
    blanball-chat-redis-dev:
      condition: service_healthy

services:
  blanball-chat-db-dev:
    container_name: blanball-chat-db-dev
    env_file:
      - .env
    image: postgres:latest
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - blaball-chat-network-dev
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 5s
      retries: 20

  blanball-chat-redis-dev:
    container_name: blanball-chat-redis-dev
    env_file:
      - .env
    image: redis:7.0.4-alpine
    volumes:
      - redis-data:/usr/src/blanball-chat-redis/storage/redis/data
    networks:
      - blaball-chat-network-dev
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 5s
      retries: 20

  blanball-chat-api-dev:
    <<: *blanball-chat-api-common-dev
    container_name: blanball-chat-api-dev
    command: api
    ports:
      - 12000:8000

  blanball-chat-celery-worker-dev:
    <<: *blanball-chat-api-common-dev
    container_name: blanball-chat-celery-worker-dev
    command: celery-worker

  blanball-chat-celery-beat-dev:
    <<: *blanball-chat-api-common-dev
    container_name: blanball-chat-celery-beat-dev
    command: celery-beat

  blanball-chat-kafka-dev:
    container_name: blanball-chat-kafka-dev
    env_file:
      - .env
    image: confluentinc/cp-kafka:latest
    depends_on:
      - blanball-chat-zookeeper-dev
    ports:
      - 9094:9092
      - 9095:9093
    restart: always
    volumes:
      - kafka-data:/usr/src/blanball-chat/storage/kafka/data
    networks:
      - blaball-chat-network-dev
      - blanball-chat-connection-network-dev

  blanball-chat-zookeeper-dev:
    container_name: blanball-chat-zookeeper-dev
    env_file:
      - .env
    image: zookeeper:latest
    ports:
      - 2183:2181
    restart: always
    volumes:
      - zookeeper-data:/usr/src/blanball-chat/storage/zookeeper/data \
      - zookeeper-logs-data:/usr/src/blanball-chat/storage/zookeeper-logs/data \
    networks:
      - blaball-chat-network-dev
      - blanball-chat-connection-network-dev


networks:
    blaball-chat-network-dev:
        name: blaball-chat-network-dev
    blanball-chat-connection-network-dev:
        name: blanball-chat-connection-network-dev

volumes:
  kafka-data:
  redis-data:
  zookeeper-data:
  zookeeper-logs-data:
