# Generated by Django 4.2.1 on 2023-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messsage",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
