# Generated by Django 4.2.1 on 2023-06-08 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_chat_author_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="event_id",
            field=models.BigIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="type",
            field=models.CharField(
                choices=[
                    ("Personal", "Personal"),
                    ("Group", "Group"),
                    ("Event_Group", "Event Group"),
                ],
                max_length=15,
            ),
        ),
    ]
