# Generated by Django 4.2.1 on 2023-06-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messsage',
            name='readed',
        ),
        migrations.AddField(
            model_name='messsage',
            name='readed_by',
            field=models.JSONField(null=True),
        ),
    ]
