# Generated by Django 4.2.1 on 2023-06-11 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_remove_messsage_readed_messsage_readed_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={
                "ordering": ["-id"],
                "verbose_name": "chat",
                "verbose_name_plural": "chats",
            },
        ),
    ]
