# Generated by Django 4.2.1 on 2023-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_chat_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="messsage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
