# Generated by Django 4.2.1 on 2023-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_messsage_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messsage",
            name="chat",
        ),
        migrations.AddField(
            model_name="chat",
            name="messages",
            field=models.ManyToManyField(
                blank=True, related_name="chat", to="chat.messsage"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="users",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="messsage",
            name="read_by",
            field=models.JSONField(default=list),
        ),
    ]
