# Generated by Django 4.2.1 on 2023-06-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_remove_messsage_chat_chat_messages_alter_chat_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messsage",
            name="reply_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="chat.messsage",
            ),
        ),
    ]
