# Generated by Django 4.2.1 on 2023-06-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_messsage_reply_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messsage",
            name="reply_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.messsage",
            ),
        ),
    ]
