# Generated by Django 4.2.1 on 2023-06-21 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_alter_chat_messages_alter_chat_name_alter_chat_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chat_request_user_id",
            field=models.BigIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
