# Generated by Django 4.2.1 on 2023-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_chat_chat_request_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="messsage",
            name="type",
            field=models.CharField(
                choices=[
                    ("user_message", "User Message"),
                    ("user_joined_to_chat", "User Joined To Chat"),
                ],
                default="user_message",
                max_length=255,
            ),
        ),
    ]
