# Generated by Django 4.2.1 on 2023-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_messsage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(db_index=True, max_length=355, null=True),
        ),
    ]
