# Generated by Django 4.2.1 on 2023-07-04 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_alter_chat_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="chat_request_user_id",
        ),
    ]
