# Generated by Django 4.2.1 on 2023-07-14 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0018_remove_chat_chat_request_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messsage",
            name="sender_id",
            field=models.BigIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="messsage",
            name="text",
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="messsage",
            name="type",
            field=models.CharField(
                choices=[
                    ("user_message", "User Message"),
                    ("user_joined_to_chat", "User Joined To Chat"),
                    ("group_chat_created", "Group Chat Created"),
                ],
                default="user_message",
                max_length=255,
            ),
        ),
    ]
